config/routes.rb
Rails.application.routes.draw do
  resources :graduates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/graduate.rb
class Graduate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/graduates_controller.rb
class GraduatesController < ApplicationController
  before_action :set_graduate, only: [:show, :edit, :update, :destroy]

  # GET /graduates
  # GET /graduates.json
  def index
    @graduates = Graduate.all
  end

  # GET /graduates/1
  # GET /graduates/1.json
  def show
  end

  # GET /graduates/new
  def new
    @graduate = Graduate.new
  end

  # GET /graduates/1/edit
  def edit
  end

  # POST /graduates
  # POST /graduates.json
  def create
    @graduate = Graduate.new(graduate_params)

    respond_to do |format|
      if @graduate.save
        format.html { redirect_to @graduate, notice: 'Graduate was successfully created.' }
        format.json { render :show, status: :created, location: @graduate }
      else
        format.html { render :new }
        format.json { render json: @graduate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /graduates/1
  # PATCH/PUT /graduates/1.json
  def update
    respond_to do |format|
      if @graduate.update(graduate_params)
        format.html { redirect_to @graduate, notice: 'Graduate was successfully updated.' }
        format.json { render :show, status: :ok, location: @graduate }
      else
        format.html { render :edit }
        format.json { render json: @graduate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /graduates/1
  # DELETE /graduates/1.json
  def destroy
    @graduate.destroy
    respond_to do |format|
      format.html { redirect_to graduates_url, notice: 'Graduate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_graduate
      @graduate = Graduate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def graduate_params
      params.require(:graduate).permit(:cedula, :nombre, :apellido, :sexo, :carrera, :telefono, :direccion, :fecha_nacimiento, :fecha_egreso)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/graduates_helper.rb
module GraduatesHelper
end

app/views/graduates/_form.html.erb
<%= form_for(graduate) do |f| %>
  <% if graduate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(graduate.errors.count, "error") %> prohibited this graduate from being saved:</h2>

      <ul>
      <% graduate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cedula %>
    <%= f.text_field :cedula %>
  </div>

  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre %>
  </div>

  <div class="field">
    <%= f.label :apellido %>
    <%= f.text_field :apellido %>
  </div>

  <div class="field">
    <%= f.label :sexo %>
    <%= f.text_field :sexo %>
  </div>

  <div class="field">
    <%= f.label :carrera %>
    <%= f.text_field :carrera %>
  </div>

  <div class="field">
    <%= f.label :telefono %>
    <%= f.text_field :telefono %>
  </div>

  <div class="field">
    <%= f.label :direccion %>
    <%= f.text_field :direccion %>
  </div>

  <div class="field">
    <%= f.label :fecha_nacimiento %>
    <%= f.date_select :fecha_nacimiento %>
  </div>

  <div class="field">
    <%= f.label :fecha_egreso %>
    <%= f.date_select :fecha_egreso %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/graduates/edit.html.erb
<h1>Editing Graduate</h1>

<%= render 'form', graduate: @graduate %>

<%= link_to 'Show', @graduate %> |
<%= link_to 'Back', graduates_path %>

app/views/graduates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Graduates</h1>

<table>
  <thead>
    <tr>
      <th>Cedula</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Sexo</th>
      <th>Carrera</th>
      <th>Telefono</th>
      <th>Direccion</th>
      <th>Fecha nacimiento</th>
      <th>Fecha egreso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @graduates.each do |graduate| %>
      <tr>
        <td><%= graduate.cedula %></td>
        <td><%= graduate.nombre %></td>
        <td><%= graduate.apellido %></td>
        <td><%= graduate.sexo %></td>
        <td><%= graduate.carrera %></td>
        <td><%= graduate.telefono %></td>
        <td><%= graduate.direccion %></td>
        <td><%= graduate.fecha_nacimiento %></td>
        <td><%= graduate.fecha_egreso %></td>
        <td><%= link_to 'Show', graduate %></td>
        <td><%= link_to 'Edit', edit_graduate_path(graduate) %></td>
        <td><%= link_to 'Destroy', graduate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Graduate', new_graduate_path %>

app/views/graduates/new.html.erb
<h1>New Graduate</h1>

<%= render 'form', graduate: @graduate %>

<%= link_to 'Back', graduates_path %>

app/views/graduates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cedula:</strong>
  <%= @graduate.cedula %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @graduate.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @graduate.apellido %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @graduate.sexo %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @graduate.carrera %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @graduate.telefono %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @graduate.direccion %>
</p>

<p>
  <strong>Fecha nacimiento:</strong>
  <%= @graduate.fecha_nacimiento %>
</p>

<p>
  <strong>Fecha egreso:</strong>
  <%= @graduate.fecha_egreso %>
</p>

<%= link_to 'Edit', edit_graduate_path(@graduate) %> |
<%= link_to 'Back', graduates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APIregistro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>